project:
  title: "Enhancing Artificial Data for the NHP Model"
  output-dir: docs
  resources:
    - images/


website:
  navbar:
    left:
      - text: "Presentation"
        href: "presentation.qmd"
      - text: "Project Report"
        href: "report.qmd"

format:
  html:
    theme:
      light: [default, su_presentation.scss]
    toc: true